### ISSUE TITLE
Native support for ACM certificate

### ISSUE THREAD

**Issue by cagataygurturk** [ryansb/acm-certs-cloudformation#5]
It seems that Cloudformation added natively the ACM certificate support but it is not documented. I accidentally discovered it.

This is how it works:

```
"ViewerCertificate": {
            "SslSupportMethod": "sni-only",
            "AcmCertificateArn": "CERTIFICATE_ARN"
},
```

Thanks for this repository but maybe you might already consider deprecating it and updating Readme. Then, people would make their CF work easily.

**Comment by ryansb** [comment]
Yeah, this repo is now basically obsolete because it's now native in CloudFormation.
